version: '3.8'

services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: testapi
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - /home/anvy/Others/DB/mongodb/go-testapi/mongodb_data_container:/data/db
